name: 'Build LaTex Document'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2.1.7
      name: Cache tectonic and fonts
      with:
        path: |
          ~/.cache/Tectonic
          ~/.local/share/fonts
        key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
        restore-keys: |
           ${{ runner.os }}-tectonic-
    - uses: wtfjoke/setup-tectonic@v1.1.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Compile TeX to PDF
      run: |
        parallel -j2 tectonic {} ::: doc/*.tex
    - name: Release
      uses: 'marvinpinto/action-automatic-releases@v1.2.1'
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        automatic_release_tag: 'latest-${{ steps.date.outputs.date }}'
        prerelease: true
        title: 'Developmental Build ${{ steps.date.outputs.date }}'
        files: |
          doc/*.pdf