name: 'Build LaTex Document'
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2.1.7
      name: Cache tectonic and fonts
      with:
        path: |
          ~/.cache/Tectonic
          ~/.local/share/fonts
        key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
        restore-keys: |
           ${{ runner.os }}-tectonic-
    - uses: wtfjoke/setup-tectonic@v1.1.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Compile TeX to PDF
      run: |
        parallel -j2 tectonic --inplace {} ::: doc/*.tex
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: main.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}